### ISSUE TITLE
Display overlaps blind selection

### ISSUE THREAD

**Issue by nh6574** [nh6574/JokerDisplay#18]
As far as I know this is the only vanilla UI element the display overlaps with. It doesn't obstruct gameplay but it can be annoying.

![image-1](https://github.com/nh6574/JokerDisplay/assets/13772405/8b198f8a-201e-4c5a-8167-da3623e6db84)

**Comment by OppositeWolf770** [comment]
I guess you could disable the overlays in the blind selection screen. That might affect a couple jokers like `Madness` and `Throwback`.

**Comment by nh6574** [comment]
> I guess you could disable the overlays in the blind selection screen. That might affect a couple jokers like `Madness` and `Throwback`.

Yeah, that could work but I feel like hiding the overlays just for blind selection would be awkward. Also if anybody wants to have that info on screen to decide whether to skip the blind or not, it would be inconvenient to hide it. Sadly, there's no much place on screen for new elements...

Information-wise they wouldn't be affected by being hidden. The display is already hidden when Jokers are flipped without any problem.

**Comment by nh6574** [comment]
You can now hide and/or collapse the display to mitigate this.
