### ISSUE TITLE
Display rental cost on rental jokers

### ISSUE THREAD

**Issue by OppositeWolf770** [nh6574/JokerDisplay#20]
`-$3 (round)`. Could be too crowded with this information, though.

**Comment by nh6574** [comment]
Jokers that show +$ (Round) already take too much space, that plus and edition would make it unreadable. I don't think it's necessary for a fixed value. If there's a mod that makes it variable I could make a separate patch that supports it maybe.

**Comment by nh6574** [comment]
Well, ended up doing it in c5312412c7a790a63e3a878d2ab1d07a31113aa7.
