### ISSUE TITLE
Joker display sees through face down cards

### ISSUE THREAD

**Issue by ImNetheN** [nh6574/JokerDisplay#22]
The display shows the chips/mult a joker will give even if the cards are face down and you're not supposed to know if they'll trigger the joker or if they'll score at all

![image](https://github.com/nh6574/JokerDisplay/assets/129611240/cb888c9f-eeb1-43d0-bd4b-99702c9621cc)

**Comment by nh6574** [comment]
Fixed in 1.26 :)

Right now it assumes the front facing cards are always going to score but this will probably change in the future.
