### ISSUE TITLE
Wonky scaling

### ISSUE THREAD

**Issue by nh6574** [nh6574/JokerDisplay#25]
When the text on a display is updated, the scale of the text might get smaller permanently.
![example 1](https://github.com/nh6574/JokerDisplay/assets/13772405/831ce361-a5d1-4763-af9f-f5365107597e)
![example 2](https://github.com/nh6574/JokerDisplay/assets/13772405/3b7f274f-993a-4c3c-b8ae-1ddbb1915b32)
![example 3](https://github.com/nh6574/JokerDisplay/assets/13772405/433b225f-5445-4cd3-a837-2c6a34807aba)

Similarly, when a Joker gets an edition it might not scale correctly
![example 4](https://github.com/nh6574/JokerDisplay/assets/13772405/db911dc3-7448-449a-956d-c77b2484527d)

I'm pretty sure these are caused by the same issue so I'm dumping them both here together.

**Comment by OppositeWolf770** [comment]
Seeing that tiny blue pixel next to Matador's description always makes me chuckle 😂

**Comment by OppositeWolf770** [comment]
Maybe you could put the edition text on top in the middle, between the perishable and rental displays? That way it doesn't interfere with the Joker's base description

**Comment by nh6574** [comment]
> Maybe you could put the edition text on top in the middle, between the perishable and rental displays? That way it doesn't interfere with the Joker's base description

I personally like having all the modifiers on the same row. With the newest refactoring I've added the ability to have an empty first row so my idea was to have modifiers on the first row and any reminder text on the second row.

But I'd prefer a generalized solution that also solves the first problem with Blueprint (this will also make it easier to let Blueprint display the actual ability of the joker next to it). The issue is that I need to get more familiar with how the UI works in this game.

**Comment by nh6574** [comment]
Mostly fixed in v1.4.0 but still needs more work
