### ISSUE TITLE
[suggested setting] Make the Poker Hand tab the default tab when opening the Run Info windows

### ISSUE THREAD

**Issue by woutercools** [nh6574/JokerDisplay#26]
During a run I have more need to view the Poker Hand tab than the History tab.

Could you change the default screen of the Run Info windows to the Poker Hands tab instead of the History tab?

Thanks.

**Comment by nh6574** [comment]
This mod doesn't change how the settings are displayed and the default tab is already poker hands. Are you sure you're not confusing this mod for another?

**Comment by woutercools** [comment]
> This mod doesn't change how any of the vanilla UI is displayed and the default tab is already poker hands. Are you sure you're not confusing this mod for another?

Oh... Indeed. You're right! It's Divvy's History mod that has this effect.

Sorry about this. You're Joker Display mod is also very awesome.
