### ISSUE TITLE
Raised fist shows +0 if lowest ranked card is in played hand

### ISSUE THREAD

**Issue by imnethen** [nh6574/JokerDisplay#34]
If the lowest ranked card out of all you have is in the hand you are going to play, raised fist shows +0 mult
![image](https://github.com/user-attachments/assets/a07c79e3-db59-4889-b3ba-5890d73f4e57)

**Comment by nh6574** [comment]
I'm not able to replicate this. Do you remember anything about the run? Did it happen in different run too? 
![image](https://github.com/user-attachments/assets/0700fad2-43a5-477e-9012-61477a354b92)

**Comment by imnethen** [comment]
i actually have the save file still, here it is [save.jkr](https://github.com/user-attachments/files/16240696/save.txt)
it's probably because of mime

**Comment by nh6574** [comment]
Yeah, it was Mime. Thank you.
