### ISSUE TITLE
Possible game crash upon selecting polychrome joker from the shop

### ISSUE THREAD

**Issue by woutercools** [nh6574/JokerDisplay#39]
I also have other QOL mods installed.
Maybe it's a because of one of those other mods.

![image](https://github.com/user-attachments/assets/92992f30-2cba-4c0a-b8e2-a099ac2b3528)

Oops! The game crashed:
[SMODS JokerDisplay "JokerDisplay.lua"]:357: attempt to index field 'config' (a nil value)

Additional Context:
Balatro Version: 1.0.1f-FULL
Modded Version: 1.0.0-ALPHA-0708a-STEAMODDED
Love2D Version: 11.5.0
Lovely Version: 0.5.0-beta5
Steamodded Mods:
    1: JokerDisplay by nh6574 [ID: JokerDisplay, Priority: -100000, Version: 1.6.1]
    2: Divvy's Simulation by Divvy C. [ID: dvsimulate, Priority: -80]
    3: BalaLib by Toeler [ID: balalib, Priority: -10]
    4: Achievements Enabler by Steamo [ID: AchievementsEnabler]
    5: Balatro Safety by Zei33 [ID: balatro-safety, Version: 1.0.0]
    6: Better Mouse And Gamepad by Kooluve [ID: BetterMouseAndGamepad]
    7: Divvy's History by Divvy C. [ID: dvhistory]
    8: Divvy's Preview by Divvy C. [ID: dvpreview]
    9: Faster Planets by boomer678 [ID: 6789321315]
    10: Fold Button by happinyz [ID: FoldButton]
    11: Four Color Deck by wout25 [ID: FourColorDeck]
    12: Hand Preview by Toeler [ID: handpreview]
    13: Choose First Shop Joker by infarctus [ID: choose_first_shop_Joker]
    14: More Speed by Steamo [ID: MoreSpeed]
    15: Quick Restart by arachnei [ID: quick_restart]
    16: Run Reviewer by MilcK [ID: RunReviewer]
    17: Stickers Always Shown ?? by SirMaiquis [ID: StickersAlwaysShown]
    18: JokerSellValue by OppositeWolf770 [ID: JokerSellValue, Priority: 100000, Version: 1.2.1]

Stack Traceback
===============
(3) Lua method 'update_joker_display' at file 'JokerDisplay.lua:357' (from mod with id JokerDisplay)
Local variables:
 self = table: 0x160d41c0  {click_offset:table: 0x15924170, added_to_deck:true, children:table: 0x16328ce0 (more...)}
 force_update = string: "CardArea.emplace"
 (*temporary) = nil
 (*temporary) = nil
 (*temporary) = string: ""
 (*temporary) = string: "modify_jokers"
 (*temporary) = table: 0x16075de0  {x:8.7597922539527, w:2.0487804878049, y:-0.060360689665874, h:2.7512195121951 (more...)}
 (*temporary) = number: 8.75979
 (*temporary) = number: 0.00735323
 (*temporary) = number: 0.28066
 (*temporary) = number: 153.654
 (*temporary) = number: 8.75244
 (*temporary) = number: 1
 (*temporary) = number: nan
 (*temporary) = string: "attempt to index field 'config' (a nil value)"
(4) Lua global 'update_all_joker_display' at file 'JokerDisplay.lua:466' (from mod with id JokerDisplay)
Local variables:
 force_update = string: "CardArea.emplace"
 (for generator) = C function: next
 (for state) = table: 0x1544e1f8  {1:table: 0x160d41c0}
 (for control) = number: nan
 k = number: 1
 v = table: 0x160d41c0  {click_offset:table: 0x15924170, added_to_deck:true, children:table: 0x16328ce0 (more...)}
(5) Lua method 'emplace' at file 'JokerDisplay.lua:1004' (from mod with id JokerDisplay)
Local variables:
 self = table: 0x15ddcd78  {click_offset:table: 0x163dce68, children:table: 0x1574f8d8, shuffle_amt:0 (more...)}
 card = table: 0x160d41c0  {click_offset:table: 0x15924170, added_to_deck:true, children:table: 0x16328ce0 (more...)}
 location = nil
 stay_flipped = nil
(6) Lua field 'func' at file 'functions/button_callbacks.lua:2415'
(7) Lua method 'handle' at file 'engine/event.lua:55'
Local variables:
 self = table: 0x161fa740  {start_timer:true, timer:TOTAL, blockable:true, trigger:after, func:function: 0x16016388 (more...)}
 _results = table: 0x1553de50  {blocking:true, pause_skip:false, time_done:true, completed:false}
(8) Lua method 'update' at file 'engine/event.lua:182'
Local variables:
 self = table: 0x157f3548  {queue_last_processed:217.35000000007, queues:table: 0x157f3570, queue_dt:0.016666666666667 (more...)}
 dt = number: 0.0139552
 forced = nil
 (for generator) = C function: next
 (for state) = table: 0x157f3570  {unlock:table: 0x157f3598, other:table: 0x157f3a10, tutorial:table: 0x157f35e8 (more...)}
 (for control) = number: nan
 k = string: "base"
 v = table: 0x157f35c0  {1:table: 0x156d3d98, 2:table: 0x161fa740, 3:table: 0x1571f100}
 blocked = boolean: false
 i = number: 2
 results = table: 0x1553de50  {blocking:true, pause_skip:false, time_done:true, completed:false}
(9) Lua upvalue 'gameUpdateRef' at file 'game.lua:2484'
Local variables:
 self = table: 0x152a3478  {PALETTE:table: 0x154a4c78, ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true (more...)}
 dt = number: 0.0139552
 http_resp = nil
(10) Lua upvalue 'orig_update' at file 'main.lua:479'
Local variables:
 self = table: 0x152a3478  {PALETTE:table: 0x154a4c78, ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true (more...)}
 dt = number: 0.0139552
(11) Lua method 'update' at file 'HandPreview.lua:331' (from mod with id handpreview)
Local variables:
 self = table: 0x152a3478  {PALETTE:table: 0x154a4c78, ANIMATION_FPS:10, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true (more...)}
 dt = number: 0.0139552
(12) Lua field 'update' at file 'main.lua:133'
Local variables:
 dt = number: 0.0139552
(13) Lua function '?' at file 'main.lua:77' (best guess)
(14) global C function 'xpcall'
(15) Love2D function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '?' (defined at line 48 of chunk main.lua)
 inerror = boolean: true
 deferErrhand = Lua function '(Love2D Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])

**Comment by nh6574** [comment]
Update Steamodded

**Comment by woutercools** [comment]
> Update Steamodded

Works now.
Thanks!
