### ISSUE TITLE
Config option to disable "Click on display to remove extra text"

### ISSUE THREAD

**Issue by OppositeWolf770** [nh6574/JokerDisplay#40]
Basically, it'd be nice to have an option to prevent that from happening. So that when you click on it nothing actually happens. For me, it would be nice to prevent it because I accidentally click on it sometimes during blind selection (and I never actually find a reason to want to disable the extra info).

Would this be something up for consideration?

**Comment by nh6574** [comment]
Yes, will do this later 👍

**Comment by nh6574** [comment]
Done :)
